language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - libgl-dev
            - libasound2-dev
      env: 
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"
    
    - os: osx
      compiler: clang
      sudo: required
      env: 
        - MATRIX_EVAL="BUILD_TYPE=Release && QT_PATH=-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"


before_install:
  - eval "${MATRIX_EVAL}"

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y                    ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  sudo apt-get update -qq                                                        ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  sudo apt-get install -qq qt511base qt511multimedia qt511translations qt511tools; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  source /opt/qt511/bin/qt511-env.sh                                             ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  export QTHOME=/opt/qt511                                                       ; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5 ninja; fi


before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${CXX} --version
  - ${CC} --version
  - cmake -GNinja -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${QT_PATH} ..

script:
  - cmake --build .
